### ISSUE TITLE
Announcements board

### ISSUE THREAD

**Issue by oana-sipos** [aludir/cafea#5]
- [x] Create announcements page
- [x] List all announcements made by all users
- [x] Create a section of your own announcements
- [x] Possibility to add, edit, delete an announcement
- [x] Sort announcements by announcer, date, tag, title
- [x] Implement pagination
- [x] Make possible to mark announcements as read
- [x] Autocomplete tag when creating announcement
- [x] Implement the tags engine
- [x] Implement comments
- [x] Take care of security
- [x] Constrain the model and add required fields

**Comment by tassos** [comment]
The autocomplete tag feature was implemented with the twitter typeahead.js in 45cbb686

**Comment by tassos** [comment]
For the sorting (b065af88), I used the methodology described here:

http://railscasts.com/episodes/228-sortable-table-columns?view=asciicast

**Comment by tassos** [comment]
Implemented the tag engine, but still need to fix the editing of the announcements

**Comment by tassos** [comment]
Productive time at the airport :)

**Comment by tassos** [comment]
@oana-sipos, we only have the pagination left for this big task. You said you could take care of it, right?

**Comment by oana-sipos** [comment]
Yes, definitely ;)

On Wed, Apr 8, 2015 at 9:56 AM, Tassos Natsakis <notifications@github.com>
wrote:

> @oana-sipos <https://github.com/oana-sipos>, we only have the pagination
> left for this big task. You said you could take care of it, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aludir/cafea/issues/5#issuecomment-90835221>.
>



-- 
Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com

**Comment by tassos** [comment]
@oana-sipos fixed this at bb222bd0
