### ISSUE TITLE
Fix database model

### ISSUE THREAD

**Issue by tassos** [aludir/cafea#9]
We made some errors when creating the tables in the database, specifically with the relationships of has_and_belongs_to_many. The name of the table must be reversed so that name of the models appear alphabetically

**Comment by tassos** [comment]
Did we fix this eventually @oana-sipos?

**Comment by oana-sipos** [comment]
To double-check. As far as I remember, we have fixed all relationships that were created the other way around than required.

**Comment by tassos** [comment]
I think we fixed everything as well. So I will mark this as closed :)
